### PR TITLE
Add John Montgomery Hero

### PR DESCRIPTION
**Pull request by jb3**
Add a hero, for my hero, looking like a hero. John Montgomery.

### CODE REVIEW

**Review by jchristgit — APPROVED** [review]
Agree! This brings the website inline with loading speeds at Nicholas Gregory's website (a leading frontend engineer)! Great work!

**Review by NicholasG04 — APPROVED** [review]
OUR hero.

**Comment by jchristgit** [comment]
I woke up this morning to the notification of this pull request closing and I have to say that I'm severely disappointed in the maintainer's handling of your changes.

As an open source maintainer like the JM03 Agency, it is your duty to respond in a fixed timeframe to important issues and outstanding pull requests, especially with great proposed changes such as this one.

I am expecting an official statement by The Agency by 3 PM CEST.

**Comment by NicholasG04** [comment]
I felt the same disappointment when I opened my email to the closure of this pull request. I sincerely hope that it can be re-opened and merged. @john-montgomery2003 to comment.

**Pull request closed without merging**
